# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d15f08bb-62b0-469f-960e-8111e0cf2aab";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9878-D9C9";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b755988d-ff7d-4f20-8eca-34159e245f58";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-81249bad-ab6b-490e-80e7-6ee8b30a1f80".device = "/dev/disk/by-uuid/81249bad-ab6b-490e-80e7-6ee8b30a1f80";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a2b1fa66-3f3c-460e-9128-2d8e555aa7d0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-27206b13-54e2-4a55-8d9c-064dd9d4cd90".device = "/dev/disk/by-uuid/27206b13-54e2-4a55-8d9c-064dd9d4cd90";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f0696fb4-7cb7-4ce4-8edc-3c5ca4be7323"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
